### ISSUE TITLE
Atlas creation fails for QGIS 3.36.2 & 3.34.6-LTR

### ISSUE THREAD

**Issue by burkmarr** [FieldStudiesCouncil/QGIS-Biological-Recording-Tools#72]
From email by David Lee:

Attempting to make a map layer fails in bioreclayer.py at line 266 with error message:
 
File "C:\Users/David/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\TomBio\bioreclayer.py", line 266, in makeFeatures self.progress.setValue(progStart + 100 * i / iLength)
TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'

**Comment by ghost** [comment]
Same on Linux, just FYI

TypeError: setValue(self, value: int): argument 1 has unexpected type 'float' 
Traceback (most recent call last):
  File "/home/mikee/.local/share/QGIS/QGIS3/profiles/default/python/plugins/TomBio/biorecdialog.py", line 839, in MapRecords
    self.createMapLayer(selectedTaxa)
  File "/home/mikee/.local/share/QGIS/QGIS3/profiles/default/python/plugins/TomBio/biorecdialog.py", line 1133, in createMapLayer
    layer.createMapLayer(self.cboMapType.currentText(), self.cboSymbol.currentText(), styleFile)
  File "/home/mikee/.local/share/QGIS/QGIS3/profiles/default/python/plugins/TomBio/bioreclayer.py", line 153, in createMapLayer
    self.addFieldsToTable(mapType)
  File "/home/mikee/.local/share/QGIS/QGIS3/profiles/default/python/plugins/TomBio/bioreclayer.py", line 250, in addFieldsToTable
    fets = self.makeFeatures(iter, iLength, mapType, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mikee/.local/share/QGIS/QGIS3/profiles/default/python/plugins/TomBio/bioreclayer.py", line 266, in makeFeatures
    self.progress.setValue(progStart + 100 * i / iLength)
TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'


Python version: 3.11.2 (main, May  2 2024, 11:59:08) [GCC 12.2.0] 
QGIS version: 3.22.16-Białowieża Białowieża, exported

**Comment by burkmarr** [comment]
Mike - this issue was fixed back in May I think. I neglected to close the issue. Are you using the latest version of the plugin?

**Comment by ghost** [comment]
Turns out I wasn't. A plugin upgrade fixed it. 
Many thanks.
